- name: Copy backend files
  become: true
  copy:
    src:  backend-dist.tar
    dest: backend-dist.tar
- name: Unarchive files  
  unarchive:
    src: backend-dist.tar
    dest: /home/ubuntu
- name: Start PM2
  become: true
  shell: |
    pm2 start backend/dist/main.js